name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit-test:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo "Stasi03"

  build_ui-test:
    needs: build_unit-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Start app
      run: npm start &
    - name: Run ui tests
      run: npm run test:ui

  deploy_render:
    runs-on: ubuntu-latest
    needs:  build_ui-test
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true
